name: Build and Publish Extension

on: [ push ] 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x
      - name: Find latest tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: jbcarreon123/WebNowPlaying-Redux-Macro-Deck
          releases-only: true
        id: wnpmd
      - name: Check Version
        run: |
          latest_release="${{ steps.octokit.outputs.tag }}"
          if [ "${{ steps.octokit.outputs.tag }}" = "${{ github.ref }}" ]; then
            echo "Version already exists. Skipping build and publish."
            exit
          fi
        shell: bash
      - name: Build Plugin
        run: |
          dotnet publish -r=windows-x64 jbcarreon123.WebNowPlayingPlugin.sln
          
